#
# Module manifest for module 'xProgress'
#
# Generated by: Mike Campbell (thatexactmike)
#
# Generated on: 10/28/2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'xProgress.psm1'

    # Version number of this module.
    ModuleVersion     = '1.1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '5e59c3b1-75fd-411f-9c40-6e8ecfeafcf8'

    # Author of this module
    Author            = 'Mike Campbell (thatexactmike)'

    # Company or vendor of this module
    CompanyName       = 'themodulecollective'

    # Copyright statement for this module
    Copyright         = '2026'

    # Description of the functionality provided by this module
    Description       = "xProgress makes progress bars in PowerShell simple: throttled Write-Progress calls, accurate percent-complete and time-remaining, and nested parent/child progress bars, all handled automatically instead of hand-rolled counter/timer/Id bookkeeping in every script. It also mirrors Write-Progress calls made inside a background job's scriptblock into your own session -- including nested activities -- via Write-xJobProgress, something no other PowerShell module does. Full stopwatch lifecycle control (Start-xProgress, Suspend-xProgress, Resume-xProgress) lets you exclude wait time such as API calls or sleeps from elapsed and time-remaining calculations."

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'New-xProgress', 'Write-xProgress', 'Complete-xProgress', 'Get-xProgress', 'Set-xProgress', 'Start-xProgress', 'Suspend-xProgress', 'Resume-xProgress', 'Write-xJobProgress'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    #CmdletsToExport = '*'

    # Variables to export from this module
    #VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = 'Initialize-xProgress'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'Progress', 'Write-Progress', 'ProgressBar', 'Jobs', 'BackgroundJobs', 'Stopwatch', 'Performance'

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/themodulecollective/xProgress/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/themodulecollective/xProgress'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = '1.1.1 - Updated module Description and Gallery Tags to reflect current functionality (background job progress mirroring, stopwatch lifecycle control). No functional code changes.

1.1.0 - Added Write-xJobProgress: mirrors progress reported by PowerShell background jobs (Write-Progress calls inside a job scriptblock) into the caller''s session via Write-Progress, preserving concurrent/nested activities.'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
