name: Main GitHub Actions
run-name: ${{ github.actor }} is using GitHub Actions 🚀
on: [push]
jobs:
  lint-with-PSScriptAnalyzer:
    name: Install and run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path *.psm1 -Recurse -Outvariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }
  test-with-pester:
    name: Run Pester tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pester
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester -MinimumVersion 5.0.0 -MaximumVersion 5.99.99 -Force -SkipPublisherCheck -ErrorAction Stop
      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module Pester -MinimumVersion 5.0.0 -MaximumVersion 5.99.99 -Force
          $result = Invoke-Pester -Path ./Tests -Output Detailed -PassThru
          if ($result.FailedCount -gt 0) {
              Write-Error "$($result.FailedCount) Pester test(s) failed." -ErrorAction Stop
          }